packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "zenstack"
  - "zenstack/packages/*"
  - "zenstack/packages/plugins/*"
  - "zenstack/packages/misc/*"
  - "zenstack/packages/ide/*"
  - "zenstack/tests/*"
